engines:
  csslint:
    enabled: false
  duplication:
    enabled: false
    checks: 
      similar code:
      enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "server/**/*.js"
exclude_paths:
  - "node_modules/"
  - "template/*"
  - "client/"
  - "server/test"
  - "dist/*"
  - "server/models/event.js"
  - "server/models/center.js"
  - "server/models/user.js"
    - "server/seeders"
