language: node_js
node_js: 
  - "stable"
script:
 -  npm run test:dev
install:
- npm install
services:
- postgresql
before_script:
 - psql -c 'create database events_manager_test;' -U postgres
after_success:
  - npm run coverage