export const SIGN_IN = 'SIGN_IN';
export const SIGN_UP = 'SIGN_UP';
export const GET_ALL_CENTERS = 'GET_ALL_CENTERS';
export const GET_TRENDING_CENTERS = 'GET_TRENDING_CENTERS';
export const ADD_CENTER = 'ADD_CENTER';
export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const GET_POPULAR_EVENTS = 'GET_POPULAR_EVENTS';
export const GET_SINGLE_CENTER = 'GET_SINGLE_CENTER';

